parameter_defaults:
    # Customize the IP subnets to match the local environment
    ControlPlaneSubnetCidr: "24"
    ControlPlaneDefaultRoute: 10.200.200.254
    EC2MetadataIp: 10.200.200.1
    ExternalInterfaceDefaultRoute: 10.200.200.1
    ExternalNetCidr: 10.200.200.1/24
    ExternalAllocationPools: [{'start': '10.200.200.101', 'end': '10.200.200.149'}]
    DnsServers: ["10.34.32.1","10.34.32.1",]
    InternalApiNetCidr: 172.21.33.0/24
    InternalApiAllocationPools: [{'start': '172.21.33.10', 'end': '172.21.33.200'}]
    StorageNetCidr: 172.21.36.0/24
    StorageMgmtNetCidr: 172.21.35.0/24
    StorageAllocationPools: [{'start': '172.21.36.10', 'end': '172.21.36.200'}]
    StorageMgmtAllocationPools: [{'start': '172.21.35.10', 'end': '172.21.35.200'}]
    TenantNetCidr: 172.16.0.0/24
    TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
    NeutronExternalNetworkBridge: "''"
