hw_env:
  env_type: qe/dell_pe_c6220_1-5
  answers_local_interface: em2
  neutron_public_interface: nic2
  libvirt_type: kvm
  network: '10.200.200'
  network_cidr: 172.21.0.0/16
  floating_ip_version: 4
  floating_ip_start: 10.200.200.2
  floating_ip_end: 10.200.200.64
  floating_ip_cidr: 10.200.200.0/24
  network_gateway: 10.200.200.1
  remote_mgmt: ipmi
  deploy_timeout: 480
  network_type: flat
  physical_network: datacentre
  ExternalNetworkVlanID: null
  dns_server: 10.34.32.1
