- name: copy our instackenv.json file if present
  template:
      src: "{{ installer.instackenv.file }}"
      dest: "~/"
  when: installer.instackenv.file is defined

- name: register our hosts to instack
  shell: "source ~/stackrc; openstack baremetal import --json instackenv.json"
  
- name: assign the kernel and ramdisk before introspection begins
  shell: "source ~/stackrc; openstack baremetal configure boot"

- name: start node introspection
  shell: "source ~/stackrc; openstack baremetal introspection bulk start"
  register: introspection_result
  failed_when: introspection_result.rc != 0
