- name: register our hosts to instack
  shell: "source ~/stackrc; openstack baremetal import --json instackenv.json"
  
- name: assign the kernel and ramdisk before introspection begins
  shell: "source ~/stackrc; openstack baremetal configure boot"

- name: start node introspection
  shell: "source ~/stackrc; openstack baremetal introspection bulk start"
  register: introspection_result
  failed_when: introspection_result.rc != 0

- name: get subnet ID to update neutron's DNS server
  shell: "source ~/stackrc; neutron subnet-list | grep '{{ undercloud_provision_cidr | ipsubnet }}' | awk '{print $2;}'"
  register: subnet_id

- name: get the nameserver
  shell: "cat /etc/resolv.conf | grep -m 1 'nameserver' | awk '{print $2}'"
  register: nameserver

- name: update neutron DNS server
  shell: "source ~/stackrc; neutron subnet-update {{ subnet_id.stdout }} --dns-nameserver {{ nameserver.stdout }}"