- name: prepare ceph storage template
  template:
      src: "ceph.yml.j2"
      dest: "{{ installer.overcloud.template_base }}/custom-ceph.yaml"
      mode: 0755

- name: append the ceph storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '--ceph-storage-scale {{ installer.nodes.storage }} \'
  when: installer.storage.external == "no"

- name: append the ceph storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '--ceph-storage-flavor {% if groups["ceph"] is defined %}ceph-{{ "ceph" | to_uuid }}{% else %}baremetal{% endif %} \'
  when: installer.storage.external == "no"

- name: append the storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e /usr/share/openstack-tripleo-heat-templates/environments/storage-environment.yaml \'

- name: append the storage ceph custom template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e {{ installer.overcloud.template_base }}/custom-ceph.yaml \'
