---
- include: pre.yml
  tags: backup

- name: Installing the undercloud
  tags: backup
  hosts: undercloud
  roles:
      - {role: installer/ospd/undercloud, when: "'undercloud' in groups"}

- name: Modify undercloud in case of virthost deployment
  tags: virthost
  include: virthost.yml
  when: "'virthost' in groups"

- name: Preparing the images
  tags:
      - images
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  roles:
      - {role: installer/ospd/images}

- name: Start introspection
  tags: introspection
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  roles:
      - {role: installer/ospd/overcloud/introspection, when: "installer.overcloud is defined"}
  vars:
      - undercloud_provision_cidr: "{{ ansible_br_ctlplane.ipv4.network }}/{{ ansible_br_ctlplane.ipv4.netmask }}"
  tasks:
      - name: get subnet ID to update neutron's DNS server
        shell: "source ~/stackrc; neutron subnet-list | grep '{{ undercloud_provision_cidr | ipsubnet }}' | awk '{print $2;}'"
        register: subnet_id

      - name: get the nameserver
        shell: "cat /etc/resolv.conf | grep -m 1 'nameserver' | awk '{print $2}'"
        register: nameserver

      - name: update neutron DNS server
        shell: "source ~/stackrc; neutron subnet-update {{ subnet_id.stdout }} --dns-nameserver {{ nameserver.stdout }}"

- name: Tag hosts with flavors
  tags: tagging
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  roles:
      - {role: installer/ospd/overcloud/tagging, when: "'overcloud_nodes' in groups"}

- name: Installing the overcloud
  tags: overcloud
  hosts: undercloud
  become: yes
  become_user: "{{ installer.user.name }}"
  pre_tasks:
      - name: create the template folder for customization
        file:
            name: "{{ installer.overcloud.template_base }}"
            state: directory

      - name: create the base overcloud deploy script
        template:
            src: "templates/overcloud_deploy.sh.j2"
            dest: "~/overcloud_deploy.sh"
            mode: 0755
  roles:
      - {role: installer/ospd/overcloud/storage, when: "installer.storage is defined and installer.storage.backend != 'none'"}
      - {role: installer/ospd/overcloud/network, when: "installer.network is defined and installer.network.isolation != 'no'"}
      - {role: installer/ospd/overcloud/ssl, when: "installer.overcloud.ssl == 'yes'"}

  tasks:
      - name: append the invocation line to the base overcloud deploy script
        lineinfile:
            dest: "~/overcloud_deploy.sh"
            line: "--log-file overcloud_deployment_{{ 100 | random }}.log &> overcloud_install.log"

      - name: the create overcloud script
        shell: "cat ~/overcloud_deploy.sh"

      - name: execute the overcloud deploy script
        shell: "bash ~/overcloud_deploy.sh"
        register: overcloud_deploy
        ignore_errors: yes

      - name: print the last few lines of the output to spot failures
        shell: "tail -n30 overcloud_install.log"

      - fail: msg="Overcloud deployment failed... :("
        when: overcloud_deploy.rc != 0

- include: post.yml

